name: Python Testing Workflow

on:
  push:
    branches:
      - main

jobs:
  display_python_version:
    name: Display Python Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Python Version
        run: python --version

  pylint_test:
    name: Pylint Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Run Pylint
        run: pylint app.py